In [ ]:
#Introduction to NumPy and its functions

# NumPy

In [1]:
import numpy as np

In [2]:
#list
simple_list = [1,2,3]

#calling array function
np.array(simple_list)

array([1, 2, 3])

In [4]:
list_of_lists = [1,2,3],[4,5,6],[7,8,9]

np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#arange function

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

In [9]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [14]:
np.linspace(0,20,10)

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

In [15]:
#identity matrix

np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [16]:
#random options : uniform between 0 and 1

np.random.rand(3,2)

array([[ 0.83383922,  0.53695466],
       [ 0.18964176,  0.90638016],
       [ 0.5248663 ,  0.81693483]])

In [17]:
#rand vs randn randoms on normaly distributed

np.random.randn(2,3)

array([[ 1.41026118,  0.25341915, -0.28819737],
       [ 0.26598345,  0.31225989,  0.60954388]])

In [20]:
#random integer distribution

np.random.randint(5,20)

8

In [21]:
np.random.randint(5,20,10)

array([12, 12, 18,  9,  7,  9,  7, 18, 13, 16])

In [26]:
sample_array = np.arange(30)

rand_array = np.random.randint(0,100,20)

print(rand_array)

[68 99 88 74 94 94 65 81 57  3  1 31 66 88 87 93 35 63 17 81]


In [27]:
sample_array.reshape(2,9)

ValueError: cannot reshape array of size 30 into shape (2,9)

In [28]:
rand_array.argmin()

10

In [29]:
sample_array.shape

(30,)

In [30]:
#matrix formatematrix not a vector
sample_array.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [34]:
#reshape

sample_array.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [35]:
sample_array.dtype

dtype('int32')

In [43]:
a = np.random.rand(3,2)

print(a)

[[ 0.13436145  0.44908566]
 [ 0.58030619  0.41928838]
 [ 0.45566577  0.95977468]]


In [44]:
a.T

array([[ 0.13436145,  0.58030619,  0.45566577],
       [ 0.44908566,  0.41928838,  0.95977468]])

# How to select group of objects from a particular array

In [46]:
#How to select group of objects from a particular array

sample_array = np.arange(10,21)
print(sample_array)

[10 11 12 13 14 15 16 17 18 19 20]


In [47]:
sample_array[8]

18

In [48]:
sample_array[[2,5]]

array([12, 15])

In [49]:
sample_array[1:2] = 100

In [50]:
sample_array

array([ 10, 100,  12,  13,  14,  15,  16,  17,  18,  19,  20])

In [51]:
sample_array = np.arange(10,21)

In [52]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [53]:
subset_sample_array = sample_array[0:7]
print(subset_sample_array)

[10 11 12 13 14 15 16]


In [54]:
#brodcasting values : assiging 1001 value to all the array value
subset_sample_array[:] = 1001

In [55]:
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [57]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [ ]:
#subset will create a view into same orginal array
#if we need to copy the array then we should use sample array we cant use subset

In [58]:
#copy of the array
copy_sample_array = sample_array.copy()

In [59]:
#broadcast value
copy_sample_array[:] = 2

In [61]:
print(copy_sample_array)
print(sample_array)

#now it just copied the value

[2 2 2 2 2 2 2 2 2 2 2]
[1001 1001 1001 1001 1001 1001 1001   17   18   19   20]


# Indexing a matrix

In [62]:
#matrix or 2dimentional array
sample_matrix = np.array(([50,20,1,23],[24,23,21,32],[2,4,1,2],[5,6,2,3]))

In [63]:
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 32],
       [ 2,  4,  1,  2],
       [ 5,  6,  2,  3]])

In [64]:
#indexing using sqare brackets
sample_matrix[0,3]

23

In [65]:
#slicing matrix
sample_matrix[0,3]

23

In [67]:
print(sample_matrix[3:])
print(sample_matrix[3])

[[5 6 2 3]]
[5 6 2 3]


In [68]:
#custom indexing of matrix
# all the rows and only 1 and 3 index position card
sample_matrix[:,(1,3)]

array([[20, 23],
       [23, 32],
       [ 4,  2],
       [ 6,  3]])

In [ ]:
#selecting all the rows and 

In [69]:
sample_matrix[:,(3,1)]

array([[23, 20],
       [32, 23],
       [ 2,  4],
       [ 3,  6]])

# Selection techniques