In [ ]:
#NumPy Overview
#Arrays
#Array Manipluations
#Advanced Array Manipulations
#Exercises

In [2]:
#numpy

import numpy as np

myPylist = [1,2,3,4]

#convert list to numpy array

numpy_array = np.array(myPylist)

print(numpy_array)
print(type(numpy_array))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
#Arrays of various data types

x = np.array([1,2,3,4])
print(x)
print(x.dtype)

y = np.array([1.0,2.0,3.0,4.0])
print(y)
print(y.dtype)


z = np.array([1,2,3,4], dtype=np.int64)
print(z)
print(z.dtype)

[1 2 3 4]
int32
[ 1.  2.  3.  4.]
float64
[1 2 3 4]
int64


In [12]:
#how numpy is memory efficient!!!
#import time

# creat a list (python) and array(numpy) of size 1000 element
#check the total memory occupany of each list


import sys

python_list = range(1000) #0 to n-1

numpy_array = np.arange(1000) #0 to n-1

print("Total size occupied by python list (bytes) ",(len(python_list)*sys.getsizeof(1)))

print("total size of numpy array (bytes) ", numpy_array.size * numpy_array.itemsize)

#numpy_array.size : return number of elements in array
#numpy_array.itemsize : return size occuped by 1 elements in numpy array

Total size occupied by python list (bytes)  28000
total size of numpy array (bytes)  4000


In [21]:
#performance factor in numpy: output in milliseconds

import time
SIZE=10000000
L1 = range(SIZE)
L2 = range(SIZE)

A1=np.arange(SIZE)
A2=np.arange(SIZE)
#python list for time tracking
start = time.time() #ticks/seconds
#time.sleep(.2)
result = [(x+y) for x,y in zip(L1,L2)] #zip will pull each item from zip and store in differt variables

end = time.time()
print("list took ",(end-start)*1000) #milliseconds ms

#list time trackiing for Numpy
start = time.time() #ticks/seconds
#time.sleep(.2)
result = A1+A2

end = time.time()
print("list took time for numpy",(end-start)*1000) #milliseconds ms

list took  20251.351356506348
list took time for numpy 2951.347589492798


In [24]:
#generating random number in numpy

print(np.random.rand(2,6)) #this generates array of given dimension and 
#number will be 1 and 0

[[ 0.34808584  0.59993906  0.44394916  0.40177828  0.16892283  0.46160729]
 [ 0.54667663  0.98694791  0.10735214  0.84073499  0.92694842  0.28466971]]


In [25]:
print(np.random.choice(['a','e','i','o','u'],size=10))

['u' 'a' 'a' 'u' 'i' 'o' 'a' 'u' 'o' 'i']


In [28]:
#shape of arrays : 1 Dim array

a = np.array([1,2,3,4]) #its a 1Dim array
print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [31]:
#creating 2D array

b = np.array([[1,2,3,4],[5,6,7,8]])

print(b.shape)

(2, 4)


In [34]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print("shape of b is ",b.shape)

#reshape the array
b = b.reshape(4,2)
print("\n\n")
print(b)

[[1 2 3 4]
 [5 6 7 8]]
shape of b is  (2, 4)



[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [36]:
#testing

a = np.array([1,2,3,4,5])
print(type(a))

print(a[0],a[1],[2])

a[0]=5
print(a)

#2D array

b = np.array([[1,2,4],[4,5,6]])

print(b[0,0],b[0,1],b[1,0])

<class 'numpy.ndarray'>
1 2 [2]
[5 2 3 4 5]
1 2 4


In [49]:
#slicing in 2D array

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(a)

#print(a.shape)

row_1 = a[1,:] # a [ row_index, column Index] here : is for all the columns

print(row_1)

row_1_copy=a[1:2,:]
print(row_1_copy)

#pull 2 and 3



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[[5 6 7 8]]


In [67]:

print(a[0,1],a[0,2],a[1,1],a[1,2])

2 3 6 7


In [75]:
#mathematical computations!

mylist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

np_arr = np.array(mylist,dtype="float")

print(np_arr)

print("Mean value is ",np_arr.mean())
print("Max value is ",np_arr.max())
print("Min value is ",np_arr.min())


#-------------------------

print("column wise mean",np.amin(np_arr,axis=0))
print("column wise mean",np.amin(np_arr,axis=1))

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]]
Mean value is  6.5
Max value is  12.0
Min value is  1.0
column wise mean [ 1.  2.  3.  4.]
column wise mean [ 1.  5.  9.]


In [ ]:
#maths with np array

In [81]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

r1 = x+y
print(r1)

r2 = x-y
print(r2)

r3 = np.subtract(x,y)
print(r3)

r4 = np.multiply(x,y)
print(r4)

r5 = np.divide(x,y)
print(r5)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [86]:
#3D array

a = np.array([[[1,2,3],[1,2,3]]])
print(a)
print(a.shape)

[[[1 2 3]
  [1 2 3]]]
(1, 2, 3)
