In [ ]:
#Introduction to NumPy and its functions

# NumPy

In [1]:
import numpy as np

In [2]:
#list
simple_list = [1,2,3]

#calling array function
np.array(simple_list)

array([1, 2, 3])

In [4]:
list_of_lists = [1,2,3],[4,5,6],[7,8,9]

np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#arange function

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

In [9]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [14]:
np.linspace(0,20,10)

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

In [15]:
#identity matrix

np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [16]:
#random options : uniform between 0 and 1

np.random.rand(3,2)

array([[ 0.83383922,  0.53695466],
       [ 0.18964176,  0.90638016],
       [ 0.5248663 ,  0.81693483]])

In [17]:
#rand vs randn randoms on normaly distributed

np.random.randn(2,3)

array([[ 1.41026118,  0.25341915, -0.28819737],
       [ 0.26598345,  0.31225989,  0.60954388]])

In [20]:
#random integer distribution

np.random.randint(5,20)

8

In [21]:
np.random.randint(5,20,10)

array([12, 12, 18,  9,  7,  9,  7, 18, 13, 16])

In [26]:
sample_array = np.arange(30)

rand_array = np.random.randint(0,100,20)

print(rand_array)

[68 99 88 74 94 94 65 81 57  3  1 31 66 88 87 93 35 63 17 81]


In [27]:
sample_array.reshape(2,9)

ValueError: cannot reshape array of size 30 into shape (2,9)

In [28]:
rand_array.argmin()

10

In [29]:
sample_array.shape

(30,)

In [30]:
#matrix formatematrix not a vector
sample_array.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [34]:
#reshape

sample_array.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [35]:
sample_array.dtype

dtype('int32')

In [43]:
a = np.random.rand(3,2)

print(a)

[[ 0.13436145  0.44908566]
 [ 0.58030619  0.41928838]
 [ 0.45566577  0.95977468]]


In [44]:
a.T

array([[ 0.13436145,  0.58030619,  0.45566577],
       [ 0.44908566,  0.41928838,  0.95977468]])

# How to select group of objects from a particular array

In [46]:
#How to select group of objects from a particular array

sample_array = np.arange(10,21)
print(sample_array)

[10 11 12 13 14 15 16 17 18 19 20]


In [47]:
sample_array[8]

18

In [48]:
sample_array[[2,5]]

array([12, 15])

In [49]:
sample_array[1:2] = 100

In [50]:
sample_array

array([ 10, 100,  12,  13,  14,  15,  16,  17,  18,  19,  20])

In [51]:
sample_array = np.arange(10,21)

In [52]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [53]:
subset_sample_array = sample_array[0:7]
print(subset_sample_array)

[10 11 12 13 14 15 16]


In [54]:
#brodcasting values : assiging 1001 value to all the array value
subset_sample_array[:] = 1001

In [55]:
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [57]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [ ]:
#subset will create a view into same orginal array
#if we need to copy the array then we should use sample array we cant use subset

In [58]:
#copy of the array
copy_sample_array = sample_array.copy()

In [59]:
#broadcast value
copy_sample_array[:] = 2

In [61]:
print(copy_sample_array)
print(sample_array)

#now it just copied the value

[2 2 2 2 2 2 2 2 2 2 2]
[1001 1001 1001 1001 1001 1001 1001   17   18   19   20]


# Indexing a matrix

In [62]:
#matrix or 2dimentional array
sample_matrix = np.array(([50,20,1,23],[24,23,21,32],[2,4,1,2],[5,6,2,3]))

In [63]:
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 32],
       [ 2,  4,  1,  2],
       [ 5,  6,  2,  3]])

In [64]:
#indexing using sqare brackets
sample_matrix[0,3]

23

In [65]:
#slicing matrix
sample_matrix[0,3]

23

In [67]:
print(sample_matrix[3:])
print(sample_matrix[3])

[[5 6 2 3]]
[5 6 2 3]


In [68]:
#custom indexing of matrix
# all the rows and only 1 and 3 index position card
sample_matrix[:,(1,3)]

array([[20, 23],
       [23, 32],
       [ 4,  2],
       [ 6,  3]])

In [ ]:
#selecting all the rows and 

In [69]:
sample_matrix[:,(3,1)]

array([[23, 20],
       [32, 23],
       [ 2,  4],
       [ 3,  6]])

# Selection techniques

In [71]:
#
sample_array=np.arange(1,31)

print(sample_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30]


In [73]:
bool = sample_array < 10

In [74]:
#selection cretria within index

sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
sample_array[sample_array < 10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
a=11

In [78]:
sample_array[sample_array < a]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
print(sample_array)

print(sample_array + sample_array)

print(sample_array - sample_array)

print(sample_array / sample_array)

print(10/sample_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50
 52 54 56 58 60]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 10.           5.           3.33333333   2.5          2.           1.66666667
   1.42857143   1.25         1.11111111   1.           0.90909091
   0.83333333   0.76923077   0.71428571   0.66666667   0.625        0.58823529
   0.55555556   0.52631579   0.5          0.47619048   0.45454545
   0.43478261   0.41666667   0.4          0.38461538   0.37037037
   0.35714286   0.34482759   0.33333333]


In [ ]:
#universal functions

In [84]:
np.sqrt(sample_array)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766,
        3.31662479,  3.46410162,  3.60555128,  3.74165739,  3.87298335,
        4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595,
        4.58257569,  4.69041576,  4.79583152,  4.89897949,  5.        ,
        5.09901951,  5.19615242,  5.29150262,  5.38516481,  5.47722558])

In [ ]:
#e to the power of or log

In [90]:
print(np.max(sample_array))
print(np.min(sample_array))
print(np.tan(sample_array))
print(np.log(sample_array))


30
1
[  1.55740772e+00  -2.18503986e+00  -1.42546543e-01   1.15782128e+00
  -3.38051501e+00  -2.91006191e-01   8.71447983e-01  -6.79971146e+00
  -4.52315659e-01   6.48360827e-01  -2.25950846e+02  -6.35859929e-01
   4.63021133e-01   7.24460662e+00  -8.55993401e-01   3.00632242e-01
   3.49391565e+00  -1.13731371e+00   1.51589471e-01   2.23716094e+00
  -1.52749853e+00   8.85165604e-03   1.58815308e+00  -2.13489670e+00
  -1.33526407e-01   1.17875355e+00  -3.27370380e+00  -2.81429605e-01
   8.87142844e-01  -6.40533120e+00]
[ 0.          0.69314718  1.09861229  1.38629436  1.60943791  1.79175947
  1.94591015  2.07944154  2.19722458  2.30258509  2.39789527  2.48490665
  2.56494936  2.63905733  2.7080502   2.77258872  2.83321334  2.89037176
  2.94443898  2.99573227  3.04452244  3.09104245  3.13549422  3.17805383
  3.21887582  3.25809654  3.29583687  3.33220451  3.36729583  3.40119738]


In [97]:
array = np.random.randn(6,6)

print(np.round(array, decimals=2))

#applying statical functions
print(np.std(array))

print(np.mean(array))

print(np.var(array))

[[ 0.78  0.24 -0.14 -0.6   0.46 -0.76]
 [-0.84 -1.47  0.73  0.75 -0.   -0.  ]
 [-0.91 -0.08  0.89 -0.17  0.08  0.54]
 [-0.87  0.41 -0.44  0.86 -1.43  0.06]
 [ 0.89  0.41 -0.25 -1.88 -0.08  1.02]
 [ 0.29  0.46  2.09  0.41  0.84 -0.23]]
0.79412908378
0.0575842311652
0.630641001706


In [98]:
sports = np.array(['golf', 'cric', 'fball', 'Cric','cric','fooseball'])

#unique values
np.unique(sports)

array(['Cric', 'cric', 'fball', 'fooseball', 'golf'], 
      dtype='<U9')

# Input output options and saving files

In [99]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [101]:
simple_array = np.arange(0,20)

print(simple_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [102]:
#saving file and its saves to jupyter space
np.save('sample_array', sample_array)

In [104]:
#saves in zip formate
#archived repositry of multiple array
np.savez('2_arrays.npz', a=sample_array, b=simple_array)

In [105]:
#loading saved files

np.load('sample_array.npy')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [106]:
archive = np.load('2_arrays.npz')

In [108]:
print(archive['a'])
print(archive['b'])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [109]:
np.savetxt('text_file.txt',sample_array,delimiter=',')

In [110]:
np.loadtxt('text_file.txt',delimiter=',')

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.])